name: state_management
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.1.0+4

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  common_dependencies:
    path: ../../common_dependencies

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
