name: common_dependencies
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.1.0+4

environment:
  sdk: ^3.1.0

dependencies:
  flutter_bloc: ^8.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
